### ISSUE TITLE
MongoDB usage on docker-compoose

### ISSUE THREAD

**Issue by enric1994** [news-scrapers/news-scraper-workers-go#1]
Hola!

I am trying to run the docker-compose but I get this error message: `news-scraper-workers-historic-go_1  | Addr: localhost:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: dial tcp 127.0.0.1:27017: connect: connection refused
`
I think the error is produced because I don't have any MongoDB instance running. In order to solve the error I added MongoDB to the docker-compose script (whithout luck):

```
  mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: news-scraped-with-tags
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
```

Can you explain how to add MongoDB to docker-compose (default username, password...) and what to do after running `docker-compose up`?

Thanks for creating this tool, keep it up!
